import { AgentId } from "../types.js";

interface DetectionResult {
  agentId: AgentId;
  confidence: number;
  modelVersion: string | null;
  promptSummary: string | null;
  signals: string[];
}

export interface CommitInfo {
  hash: string;
  message: string;
  body: string;
  author: string;
  email: string;
  trailers: string;
}

export function detectAgent(commit: CommitInfo): DetectionResult {
  const signals: string[] = [];
  let agentId: AgentId = "human";
  let confidence = 0;
  let modelVersion: string | null = null;
  let promptSummary: string | null = null;

  const detectors = [
    detectClaudeCode,
    detectCursor,
    detectCopilot,
    detectDevin,
    detectAider,
    detectGenericAI,
  ];

  for (const detector of detectors) {
    const result = detector(commit);
    if (result.matched && result.confidence > confidence) {
      agentId = result.agentId;
      confidence = result.confidence;
      modelVersion = result.modelVersion;
      if (result.promptSummary) promptSummary = result.promptSummary;
      signals.push(...result.signals);
    }
  }

  return { agentId, confidence, modelVersion, promptSummary, signals };
}

interface DetectorResult {
  matched: boolean;
  agentId: AgentId;
  confidence: number;
  modelVersion: string | null;
  promptSummary: string | null;
  signals: string[];
}

function detectClaudeCode(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;
  let modelVersion: string | null = null;

  const fullText = commit.trailers + "\n" + commit.body;

  const coAuthorMatch = fullText.match(
    /Co-[Aa]uthored-[Bb]y:\s*[Cc]laude[^<]*<(?:claude@anthropic\.com|noreply@anthropic\.com)>/i
  );
  if (coAuthorMatch) {
    signals.push("co-authored-by-claude-trailer");
    confidence = 0.95;

    const versionMatch = coAuthorMatch[0].match(
      /[Cc]laude\s+((?:Opus|Sonnet|Haiku)\s*[\d.]+(?:\s*\([^)]+\))?)/
    );
    if (versionMatch) {
      modelVersion = `Claude ${versionMatch[1].trim()}`;
    }
  }

  if (
    commit.body.includes("Generated by Claude Code") ||
    commit.body.includes("Generated with Claude Code")
  ) {
    signals.push("claude-code-generation-marker");
    confidence = Math.max(confidence, 0.95);
  }

  return {
    matched: signals.length > 0,
    agentId: "claude-code",
    confidence,
    modelVersion,
    promptSummary: null,
    signals,
  };
}

function detectCursor(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  if (commit.author === "cursor[bot]" || commit.email.includes("cursor[bot]")) {
    signals.push("cursor-bot-author");
    confidence = 0.95;
  }

  if (fullText.match(/Co-[Aa]uthored-[Bb]y:\s*Cursor Agent\s*<cursoragent@cursor\.com>/i)) {
    signals.push("cursor-agent-co-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (fullText.match(/Co-[Aa]uthored-[Bb]y:\s*cursor-agent\s*<cursor-agent@cursor\.sh>/i)) {
    signals.push("cursor-agent-co-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.body.includes("Applied via @cursor push command")) {
    signals.push("cursor-push-command");
    confidence = Math.max(confidence, 0.9);
  }

  if (commit.trailers.match(/Made-with:\s*Cursor/i)) {
    signals.push("made-with-cursor-trailer");
    confidence = Math.max(confidence, 0.85);
  }

  if (commit.body.includes("Generated by Cursor")) {
    signals.push("cursor-generation-marker");
    confidence = Math.max(confidence, 0.9);
  }

  return {
    matched: signals.length > 0,
    agentId: "cursor",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectCopilot(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  const copilotEmails = [
    "copilot@github.com",
    "175728472+Copilot@users.noreply.github.com",
    "223556219+Copilot@users.noreply.github.com",
  ];

  for (const email of copilotEmails) {
    if (fullText.includes(email)) {
      signals.push("copilot-co-authored-trailer");
      confidence = 0.95;
      break;
    }
  }

  if (
    commit.author === "copilot-swe-agent[bot]" ||
    commit.email.includes("198982749+Copilot@users.noreply.github.com")
  ) {
    signals.push("copilot-swe-agent-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.trailers.match(/Agent-Logs-Url:/i)) {
    signals.push("copilot-agent-logs-trailer");
    confidence = Math.max(confidence, 0.9);
  }

  if (commit.body.includes("copilot-workspace")) {
    signals.push("copilot-workspace-marker");
    confidence = Math.max(confidence, 0.8);
  }

  return {
    matched: signals.length > 0,
    agentId: "copilot",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectDevin(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  if (
    commit.email === "158243242+devin-ai-integration[bot]@users.noreply.github.com" ||
    commit.email.includes("devin-ai-integration[bot]")
  ) {
    signals.push("devin-bot-author");
    confidence = 0.95;
  }

  if (commit.author === "Devin AI") {
    signals.push("devin-author-name");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.body.includes("devin.ai") || commit.body.includes("Devin AI")) {
    signals.push("devin-body-marker");
    confidence = Math.max(confidence, 0.8);
  }

  return {
    matched: signals.length > 0,
    agentId: "devin",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectAider(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;
  let modelVersion: string | null = null;

  const fullText = commit.trailers + "\n" + commit.body;

  const aiderMatch = fullText.match(
    /Co-[Aa]uthored-[Bb]y:\s*aider\s*\(([^)]+)\)\s*<aider@aider\.chat>/i
  );
  if (aiderMatch) {
    signals.push("aider-co-authored-trailer");
    confidence = 0.95;
    modelVersion = aiderMatch[1].trim();
  }

  if (!aiderMatch && fullText.includes("aider@aider.chat")) {
    signals.push("aider-email");
    confidence = Math.max(confidence, 0.85);
  }

  if (commit.message.match(/^aider:/i)) {
    signals.push("aider-message-prefix");
    confidence = Math.max(confidence, 0.9);
  }

  return {
    matched: signals.length > 0,
    agentId: "aider",
    confidence,
    modelVersion,
    promptSummary: null,
    signals,
  };
}

function detectGenericAI(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  const nonAiBots = ["dependabot", "renovate", "greenkeeper", "snyk-bot", "mergify"];
  const isNonAiBot = nonAiBots.some((bot) =>
    fullText.toLowerCase().includes(bot)
  );

  if (
    !isNonAiBot &&
    fullText.match(/Co-[Aa]uthored-[Bb]y:.*(ai|assistant|agent|llm)/i)
  ) {
    signals.push("generic-ai-co-author");
    confidence = 0.6;
  }

  if (
    commit.body.match(
      /generated\s+(by|with|using)\s+(an?\s+)?(ai|llm|assistant|agent)/i
    )
  ) {
    signals.push("ai-generation-mention-in-body");
    confidence = Math.max(confidence, 0.5);
  }

  return {
    matched: signals.length > 0,
    agentId: "unknown-ai",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}
