import { AgentId } from "../types.js";

// The tools we detect from specific, documented metadata signatures (bot logins,
// dedicated co-author emails, author identities) — each verified against real
// commits on GitHub, so false-positive risk is negligible.
// "unknown-ai" (generic co-author/body hints) is deliberately NOT in this set:
// it is low-signal and excluded from headline counts unless explicitly opted in.
//
// Deliberately EXCLUDED (verified type:Bot but review-only — they comment on PRs,
// they do not author commits, so they never appear as a commit author):
//   chatgpt-codex-connector[bot], gemini-code-assist[bot], gemini-cli[bot],
//   amazon-q-developer[bot], openhands-reviewer[bot], jetbrains-ai[bot],
//   sourcegraph-cody[bot], cody[bot], replit[bot].
// Editor tools that commit under the user's own identity with no trailer
// (Windsurf/Codeium, Continue, Cline/Roo, Zed, Tabnine) are unattributable
// from metadata by design and are intentionally not guessed at.
export const BRANDED_AGENTS: AgentId[] = [
  "claude-code",
  "cursor",
  "copilot",
  "devin",
  "aider",
  "codex",
  "gemini",
  "jules",
  "openhands",
  "sweep",
  "jetbrains",
  "augment",
];

export function isBrandedAgent(id: AgentId): boolean {
  return (BRANDED_AGENTS as string[]).includes(id);
}

interface DetectionResult {
  agentId: AgentId;
  confidence: number;
  modelVersion: string | null;
  promptSummary: string | null;
  signals: string[];
}

export interface CommitInfo {
  hash: string;
  message: string;
  body: string;
  author: string;
  email: string;
  trailers: string;
}

export function detectAgent(commit: CommitInfo): DetectionResult {
  const signals: string[] = [];
  let agentId: AgentId = "human";
  let confidence = 0;
  let modelVersion: string | null = null;
  let promptSummary: string | null = null;

  const detectors = [
    detectClaudeCode,
    detectCursor,
    detectCopilot,
    detectDevin,
    detectAider,
    detectCodex,
    detectGemini,
    detectJules,
    detectOpenHands,
    detectSweep,
    detectJetBrains,
    detectAugment,
    detectGenericAI,
  ];

  for (const detector of detectors) {
    const result = detector(commit);
    if (result.matched && result.confidence > confidence) {
      agentId = result.agentId;
      confidence = result.confidence;
      modelVersion = result.modelVersion;
      if (result.promptSummary) promptSummary = result.promptSummary;
      signals.push(...result.signals);
    }
  }

  return { agentId, confidence, modelVersion, promptSummary, signals };
}

interface DetectorResult {
  matched: boolean;
  agentId: AgentId;
  confidence: number;
  modelVersion: string | null;
  promptSummary: string | null;
  signals: string[];
}

function detectClaudeCode(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;
  let modelVersion: string | null = null;

  const fullText = commit.trailers + "\n" + commit.body;

  const coAuthorMatch = fullText.match(
    /Co-[Aa]uthored-[Bb]y:\s*[Cc]laude[^<]*<(?:claude@anthropic\.com|noreply@anthropic\.com)>/i
  );
  if (coAuthorMatch) {
    signals.push("co-authored-by-claude-trailer");
    confidence = 0.95;

    const versionMatch = coAuthorMatch[0].match(
      /[Cc]laude\s+((?:Opus|Sonnet|Haiku)\s*[\d.]+(?:\s*\([^)]+\))?)/
    );
    if (versionMatch) {
      modelVersion = `Claude ${versionMatch[1].trim()}`;
    }
  }

  if (
    commit.body.includes("Generated by Claude Code") ||
    commit.body.includes("Generated with Claude Code")
  ) {
    signals.push("claude-code-generation-marker");
    confidence = Math.max(confidence, 0.95);
  }

  return {
    matched: signals.length > 0,
    agentId: "claude-code",
    confidence,
    modelVersion,
    promptSummary: null,
    signals,
  };
}

function detectCursor(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  if (commit.author === "cursor[bot]" || commit.email.includes("cursor[bot]")) {
    signals.push("cursor-bot-author");
    confidence = 0.95;
  }

  // Direct authorship: Cursor Agent <cursoragent@cursor.com>
  if (commit.email === "cursoragent@cursor.com" || commit.author === "Cursor Agent") {
    signals.push("cursor-agent-author");
    confidence = Math.max(confidence, 0.95);
  }

  // Co-author patterns (multiple formats seen in the wild)
  if (fullText.match(/Co-[Aa]uthored-[Bb]y:\s*(?:Cursor|Cursor Agent)\s*<cursoragent@cursor\.com>/i)) {
    signals.push("cursor-agent-co-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (fullText.match(/Co-[Aa]uthored-[Bb]y:\s*cursor-agent\s*<cursor-agent@cursor\.sh>/i)) {
    signals.push("cursor-agent-co-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.body.includes("Applied via @cursor push command")) {
    signals.push("cursor-push-command");
    confidence = Math.max(confidence, 0.9);
  }

  if (commit.trailers.match(/Made-with:\s*Cursor/i)) {
    signals.push("made-with-cursor-trailer");
    confidence = Math.max(confidence, 0.85);
  }

  if (commit.body.includes("Generated by Cursor")) {
    signals.push("cursor-generation-marker");
    confidence = Math.max(confidence, 0.9);
  }

  return {
    matched: signals.length > 0,
    agentId: "cursor",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectCopilot(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  const copilotEmails = [
    "copilot@github.com",
    "175728472+Copilot@users.noreply.github.com",
    "223556219+Copilot@users.noreply.github.com",
  ];

  for (const email of copilotEmails) {
    if (fullText.includes(email)) {
      signals.push("copilot-co-authored-trailer");
      confidence = 0.95;
      break;
    }
  }

  if (
    commit.author === "copilot-swe-agent[bot]" ||
    commit.email.includes("198982749+Copilot@users.noreply.github.com")
  ) {
    signals.push("copilot-swe-agent-author");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.trailers.match(/Agent-Logs-Url:/i)) {
    signals.push("copilot-agent-logs-trailer");
    confidence = Math.max(confidence, 0.9);
  }

  if (commit.body.includes("copilot-workspace")) {
    signals.push("copilot-workspace-marker");
    confidence = Math.max(confidence, 0.8);
  }

  return {
    matched: signals.length > 0,
    agentId: "copilot",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectDevin(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  if (
    commit.email === "158243242+devin-ai-integration[bot]@users.noreply.github.com" ||
    commit.email.includes("devin-ai-integration[bot]")
  ) {
    signals.push("devin-bot-author");
    confidence = 0.95;
  }

  // Devin also commits directly as "Devin <bot@devin.ai>".
  if (commit.email === "bot@devin.ai" || commit.email.includes("bot@devin.ai")) {
    signals.push("devin-bot-email");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.author === "Devin AI") {
    signals.push("devin-author-name");
    confidence = Math.max(confidence, 0.95);
  }

  if (commit.body.includes("devin.ai") || commit.body.includes("Devin AI")) {
    signals.push("devin-body-marker");
    confidence = Math.max(confidence, 0.8);
  }

  return {
    matched: signals.length > 0,
    agentId: "devin",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectAider(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;
  let modelVersion: string | null = null;

  const fullText = commit.trailers + "\n" + commit.body;

  // Aider's co-author email moved from aider@aider.chat to noreply@aider.chat;
  // accept both, with or without the "(model)" segment.
  const aiderMatch = fullText.match(
    /Co-[Aa]uthored-[Bb]y:\s*aider\s*\(([^)]+)\)\s*<(?:aider|noreply)@aider\.chat>/i
  );
  if (aiderMatch) {
    signals.push("aider-co-authored-trailer");
    confidence = 0.95;
    modelVersion = aiderMatch[1].trim();
  }

  if (
    !aiderMatch &&
    (fullText.includes("aider@aider.chat") || fullText.includes("noreply@aider.chat"))
  ) {
    signals.push("aider-email");
    confidence = Math.max(confidence, 0.85);
  }

  if (commit.message.match(/^aider:/i)) {
    signals.push("aider-message-prefix");
    confidence = Math.max(confidence, 0.9);
  }

  return {
    matched: signals.length > 0,
    agentId: "aider",
    confidence,
    modelVersion,
    promptSummary: null,
    signals,
  };
}

// ── Newer tools — verified bot logins / dedicated co-author emails ──────
// Each signature below was confirmed against real commits on GitHub (the
// account is type:Bot or a dedicated AI identity AND actually authors commits),
// so all match at high confidence with negligible false-positive risk.

function detectCodex(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  // OpenAI Codex CLI default trailer: "Co-authored-by: Codex <noreply@openai.com>"
  if (fullText.match(/Co-[Aa]uthored-[Bb]y:\s*Codex\s*<noreply@openai\.com>/i)) {
    signals.push("codex-co-author-trailer");
    confidence = 0.95;
  }

  // OpenAI Codex GitHub App accounts (codex[bot], openai-codex[bot]). The
  // review-only chatgpt-codex-connector[bot] is intentionally NOT matched.
  if (
    commit.email.includes("codex[bot]") ||
    commit.author === "codex[bot]" ||
    commit.author === "openai-codex[bot]"
  ) {
    signals.push("codex-bot-author");
    confidence = Math.max(confidence, 0.95);
  }

  return {
    matched: signals.length > 0,
    agentId: "codex",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectGemini(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body + "\n" + commit.email;

  // gemini-cli co-author trailer, e.g. "<218195315+gemini-cli@users.noreply.github.com>"
  if (fullText.includes("gemini-cli@users.noreply.github.com")) {
    signals.push("gemini-cli-co-author");
    confidence = 0.95;
  }

  return {
    matched: signals.length > 0,
    agentId: "gemini",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectJules(commit: CommitInfo): DetectorResult {
  const matched =
    commit.author === "google-labs-jules[bot]" ||
    commit.email.includes("google-labs-jules[bot]");
  return {
    matched,
    agentId: "jules",
    confidence: matched ? 0.95 : 0,
    modelVersion: null,
    promptSummary: null,
    signals: matched ? ["jules-bot-author"] : [],
  };
}

function detectOpenHands(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  // OpenHands commits as the "openhands-agent" identity...
  if (commit.author === "openhands-agent" || commit.email.includes("openhands-agent")) {
    signals.push("openhands-agent-author");
    confidence = 0.95;
  }

  // ...or attributes via a co-author trailer on the all-hands.dev domain.
  if (fullText.match(/Co-[Aa]uthored-[Bb]y:[^\n]*openhands@all-hands\.dev/i)) {
    signals.push("openhands-co-author");
    confidence = Math.max(confidence, 0.9);
  }

  return {
    matched: signals.length > 0,
    agentId: "openhands",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}

function detectSweep(commit: CommitInfo): DetectorResult {
  const matched = ["sweep-ai-deprecated[bot]", "sweep-nightly[bot]"].some(
    (login) => commit.author === login || commit.email.includes(login)
  );
  return {
    matched,
    agentId: "sweep",
    confidence: matched ? 0.95 : 0,
    modelVersion: null,
    promptSummary: null,
    signals: matched ? ["sweep-bot-author"] : [],
  };
}

function detectJetBrains(commit: CommitInfo): DetectorResult {
  // JetBrains Junie autonomous coding agent.
  const matched =
    commit.author === "jetbrains-junie[bot]" ||
    commit.email.includes("jetbrains-junie[bot]");
  return {
    matched,
    agentId: "jetbrains",
    confidence: matched ? 0.95 : 0,
    modelVersion: null,
    promptSummary: null,
    signals: matched ? ["jetbrains-junie-bot-author"] : [],
  };
}

function detectAugment(commit: CommitInfo): DetectorResult {
  const matched =
    commit.author === "augmentcode[bot]" ||
    commit.email.includes("augmentcode[bot]");
  return {
    matched,
    agentId: "augment",
    confidence: matched ? 0.95 : 0,
    modelVersion: null,
    promptSummary: null,
    signals: matched ? ["augment-bot-author"] : [],
  };
}

function detectGenericAI(commit: CommitInfo): DetectorResult {
  const signals: string[] = [];
  let confidence = 0;

  const fullText = commit.trailers + "\n" + commit.body;

  const nonAiBots = ["dependabot", "renovate", "greenkeeper", "snyk-bot", "mergify"];
  const isNonAiBot = nonAiBots.some((bot) =>
    fullText.toLowerCase().includes(bot)
  );

  // Word boundaries + same-line matching only. Without \b, the alternation
  // matched substrings inside ordinary text — e.g. "ai" inside "gm[ai]l.com",
  // "hot[mai]l", "Cl[ai]re", "Mikh[ai]l" — flagging human commits as AI.
  if (
    !isNonAiBot &&
    fullText.match(/Co-[Aa]uthored-[Bb]y:[^\n]*\b(?:ai|assistant|agent|llm)\b/i)
  ) {
    signals.push("generic-ai-co-author");
    confidence = 0.6;
  }

  if (
    commit.body.match(
      /generated\s+(?:by|with|using)\s+(?:an?\s+)?\b(?:ai|llm|assistant|agent)\b/i
    )
  ) {
    signals.push("ai-generation-mention-in-body");
    confidence = Math.max(confidence, 0.5);
  }

  return {
    matched: signals.length > 0,
    agentId: "unknown-ai",
    confidence,
    modelVersion: null,
    promptSummary: null,
    signals,
  };
}
